version: "3.7"
# Base for running docker

volumes:
  odoo_data:
  postgres_odoo:

services:
  odoo:
    build: .
    env_file: .env
    
    restart: unless-stopped

    ports: ["8069:8069", "8072:8072", "41234:41234"]

    volumes:
      - odoo_data:${ODOO_DATA_DIR}
      - ./custom:${ODOO_EXTRA_ADDONS}:cached
    command: ["odoo", "--dev", "xml"]
    depends_on:
      - db

  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - postgres_odoo:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata
